name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  ZIP_FILE: /tmp/vsag-sqlite.zip

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt install -y gfortran libomp-15-dev lcov
      - name: Build
        run: |
          cargo build --release
          SO_FILE=$(find target -name libvsag.so | head -n1)
          echo "SO_FILE=${SO_FILE}" >> $GITHUB_ENV
          zip -j ${{ env.ZIP_FILE }} "${SO_FILE}" target/release/libvsag_sqlite.so
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: |
            ${{ env.SO_FILE }}
            target/release/libvsag_sqlite.so
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.ZIP_FILE }}
          asset_name: vsag-sqlite
          tag: ${{ github.ref }}
      - name: Print so path
        if: always()
        run: |
          find target -name libvsag*.so
